"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clientsRoutes = void 0;
const express_1 = require("express");
const client_controller_1 = require("../controllers/client_controller");
const user_middleware_1 = require("../middleware/user_middleware");
const clientsRoutes = (0, express_1.Router)();
exports.clientsRoutes = clientsRoutes;
clientsRoutes.post('/clients', client_controller_1.crearCliente);
clientsRoutes.get('/clients', client_controller_1.getClientes);
clientsRoutes.put('/clients', user_middleware_1.authenticateToken, client_controller_1.updateCliente);
clientsRoutes.delete('/clients/:id', user_middleware_1.authenticateToken, client_controller_1.deleteCliente);
clientsRoutes.get('/clients/:id', client_controller_1.getClienteById);
