"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contactsRoutes = void 0;
const express_1 = require("express");
const contact_controller_1 = require("../controllers/contact_controller");
const user_middleware_1 = require("../middleware/user_middleware");
const contactsRoutes = (0, express_1.Router)();
exports.contactsRoutes = contactsRoutes;
contactsRoutes.post('/contacts', contact_controller_1.crearContact);
contactsRoutes.get('/contacts', contact_controller_1.getContacts);
contactsRoutes.put('/contacts', user_middleware_1.authenticateToken, contact_controller_1.updateContact);
contactsRoutes.delete('/contacts/:id', user_middleware_1.authenticateToken, contact_controller_1.deleteContact);
contactsRoutes.get('/contacts/:id', contact_controller_1.getContactById);
