"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.productosRoutes = void 0;
const express_1 = require("express");
const product_controller_1 = require("../controllers/product_controller");
const user_middleware_1 = require("../middleware/user_middleware");
const productosRoutes = (0, express_1.Router)();
exports.productosRoutes = productosRoutes;
productosRoutes.post('/products', user_middleware_1.authenticateToken, product_controller_1.crearProducto);
productosRoutes.get('/products', product_controller_1.getProductos);
productosRoutes.put('/products', user_middleware_1.authenticateToken, product_controller_1.updateProducto);
productosRoutes.delete('/products/:id', user_middleware_1.authenticateToken, product_controller_1.deleteProducto);
productosRoutes.get('/products/:id', user_middleware_1.authenticateToken, product_controller_1.getProductoById);
