"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.usersRoutes = void 0;
const express_1 = require("express");
const user_controller_1 = require("../controllers/user_controller");
const user_middleware_1 = require("../middleware/user_middleware");
const usersRoutes = (0, express_1.Router)();
exports.usersRoutes = usersRoutes;
usersRoutes.post('/users', user_middleware_1.authenticateToken, user_controller_1.crearUsuario);
usersRoutes.post('/getUsers', user_controller_1.getUsuarios);
